FROM node:24 AS builder

WORKDIR /app

RUN corepack enable

COPY . .

RUN pnpm install
RUN pnpm test
RUN pnpm lint
RUN pnpm build

FROM nginx:alpine AS runner

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/dist .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]