FROM node:24 AS builder

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./

#RUN pnpm install --frozen-lockfile
RUN pnpm install

COPY index.html vite.config.ts tsconfig.json tsconfig.app.json tsconfig.node.json eslint.config.js ./
COPY public ./public
COPY src ./src

RUN pnpm lint
RUN pnpm build

COPY test ./test
RUN pnpm test

FROM nginx:alpine AS runner

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/dist .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]